services:
  client_customer:
    restart: unless-stopped
    container_name: alipacno-customer-frontend
    image: ghcr.io/runtime-terror-rt/alipacno-customer-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - NODE_ENV=production
        - NEXT_TELEMETRY_DISABLED=1
        - NEXT_PUBLIC_API_URL=https://api.pacinos.uk
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=https://api.pacinos.uk
    ports:
      - "3000:3000"
